<a href="https://colab.research.google.com/github/MohammadrezaPourreza/Scikit-learn-tutorial/blob/main/LinearRegression_Modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [5]:
X = np.array([[1,1],[1,2],[2,2],[2,3]])
y = np.dot(X, np.array([1,2])) + 3
y

array([ 6,  8,  9, 11])

fit_intercept − Boolean, optional, default True

Used to calculate the intercept for the model. No intercept will be used in the calculation if this set to false.

normalize − Boolean, optional, default False

If this parameter is set to True, the regressor X will be normalized before regression. The normalization will be done by subtracting the mean and dividing it by L2 norm. If fit_intercept = False, this parameter will be ignored.

	
copy_X − Boolean, optional, default True

By default, it is true which means X will be copied. But if it is set to false, X may be overwritten.

	
n_jobs − int or None, optional(default = None)

It represents the number of jobs to use for the computation.

In [8]:
regression = LinearRegression(fit_intercept=True,normalize=True,copy_X=True,n_jobs=2).fit(X,y)
regression.predict(np.array([[3,5]]))

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,


array([16.])

In [10]:
regression.score(X,y)

1.0

In [11]:
regression.coef_

array([1., 2.])

In [12]:
regression.intercept_

3.0000000000000018