<a href="https://colab.research.google.com/github/MohammadrezaPourreza/Scikit-learn-tutorial/blob/main/PolynomialFeatures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Polynomial features can help to capture non-linear relation separator by increasing the numbr of features and increasing the dimensionality

**PARAMETERS**

degree − integer, default = 2

It represents the degree of the polynomial features.

interaction_only − Boolean, default = false

By default, it is false but if set as true, the features that are products of most degree distinct input features, are produced. Such features are called interaction features. if X and Y are featrures with interaction_only set to True we don't get X^2 and Y^2 we just get XY

include_bias − Boolean, default = true

It includes a bias column i.e. the feature in which all polynomials powers are zero.

	
order − str in {‘C’, ‘F’}, default = ‘C’

This parameter represents the order of output array in the dense case. ‘F’ order means faster to compute but on the other hand, it may slow down subsequent estimators.

In [1]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np
Y = np.arange(8).reshape(4, 2)
Y

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [2]:
poly = PolynomialFeatures(degree=2)
poly.fit_transform(Y)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.],
       [ 1.,  6.,  7., 36., 42., 49.]])

In [3]:
poly = PolynomialFeatures(degree=2,include_bias=False)
poly.fit_transform(Y)

array([[ 0.,  1.,  0.,  0.,  1.],
       [ 2.,  3.,  4.,  6.,  9.],
       [ 4.,  5., 16., 20., 25.],
       [ 6.,  7., 36., 42., 49.]])