<a href="https://colab.research.google.com/github/MohammadrezaPourreza/Scikit-learn-tutorial/blob/main/SVC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

SVMs can bu used for classification, regression and outliers' detection

SVMs are popular and memory efficient because they use a subset of training points in the decision function.

**SVC**

This class handles the multiclass support according to one-vs-one scheme.

**Parameters**

The C parameter tells the SVM optimization how much you want to avoid misclassifying each training example.

kernel − string, optional, default = ‘rbf’
This parameter specifies the type of kernel to be used in the algorithm. we can choose any one among, ‘linear’, ‘poly’, ‘rbf’, ‘sigmoid’, ‘precomputed’. The default value of kernel would be ‘rbf’

degree − int, optional, default = 3

It represents the degree of the ‘poly’ kernel function and will be ignored by all other kernels.

	
gamma − {‘scale’, ‘auto’} or float,

It is the kernel coefficient for kernels ‘rbf’, ‘poly’ and ‘sigmoid’.

coef0 − float, optional, Default=0.0

An independent term in kernel function which is only significant in ‘poly’ and ‘sigmoid’.

tol − float, optional, default = 1.e-3

This parameter represents the stopping criterion for iterations.

shrinking − Boolean, optional, default = True

This parameter represents that whether we want to use shrinking heuristic or no

	
probability − boolean, optional, default = true

This parameter enables or disables probability estimates. The default value is false, but it must be enabled before we call fit.

cache_size − float, optional

This parameter will specify the size of the kernel cache. The value will be in MB(MegaBytes).

cache_size − float, optional

This parameter will specify the size of the kernel cache. The value will be in MB(MegaBytes).

break_ties − boolean, optional, default = false

True − The predict will break ties according to the confidence values of decision_function

False − The predict will return the first class among the tied classes.

In [1]:
import numpy as np
X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]])
y = np.array([1, 1, 2, 2])
from sklearn.svm import SVC
SVCClf = SVC(kernel = 'linear',gamma = 'scale', shrinking = False,)
SVCClf.fit(X, y)

SVC(kernel='linear', shrinking=False)

In [2]:
SVCClf.coef_

array([[0.5, 0.5]])

In [3]:
SVCClf.predict([[-0.5,-0.8]])

array([1])

In [4]:
SVCClf.n_support_

array([1, 1], dtype=int32)

In [5]:
SVCClf.support_vectors_

array([[-1., -1.],
       [ 1.,  1.]])

In [6]:
SVCClf.support_

array([0, 2], dtype=int32)

In [7]:
SVCClf.fit_status_

0

nuSVC

It is like SVC but NuSVC accepts slightly different sets of parameters. The parameter which is different from SVC is as follows −

nu − float, optional, default = 0.5

nu is similar to C parameter of SVC but it is more interpretable and bounded between 0 and 1

In [8]:
import numpy as np
X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]])
y = np.array([1, 1, 2, 2])
from sklearn.svm import NuSVC
NuSVCClf = NuSVC(kernel = 'linear',gamma = 'scale', shrinking = False,)
NuSVCClf.fit(X, y)

NuSVC(kernel='linear', shrinking=False)

LinearSVC

It is similar to SVC having kernel = ‘linear’. The difference between them is that LinearSVC implemented in terms of liblinear while SVC is implemented in libsvm. That’s the reason LinearSVC has more flexibility in the choice of penalties and loss functions. It also scales better to large number of samples.

However, it supports penalty and loss parameters as follows −

penalty − string, L1 or L2(default = ‘L2’)

This parameter is used to specify the norm (L1 or L2) used in penalization (regularization).

loss − string, hinge, squared_hinge (default = squared_hinge)

It represents the loss function where ‘hinge’ is the standard SVM loss and ‘squared_hinge’ is the square of hinge loss.

In [9]:
from sklearn.svm import LinearSVC
from sklearn.datasets import make_classification
X, y = make_classification(n_features = 4, random_state = 0)
LSVCClf = LinearSVC(dual = False, random_state = 0, penalty = 'l1',tol = 1e-5)
LSVCClf.fit(X, y)

LinearSVC(dual=False, penalty='l1', random_state=0, tol=1e-05)

In [10]:
LSVCClf.predict([[0,0,0,0]])

array([1])